#!/bin/bash

set -eo pipefail

#
# This script handles all operations that must be done when a
# pull request is merged back into the master branch.
#
if [[ $CIRCLE_BRANCH != "main" ]] ; then
  exit 0
fi

echo "Pantheon test environment is $TERMINUS_SITE.$TERMINUS_ENV"

# Merge the multidev for the PR into the dev environment
terminus -n build:env:merge "$TERMINUS_SITE.$TERMINUS_ENV" --yes --delete

# Run updatedb on the dev environment
terminus -n drush $TERMINUS_SITE.dev -- updatedb --yes

# Rebuild the cache before importing the config
terminus -n drush "$TERMINUS_SITE.dev" -- cr

# Remove problematic config before importing config.
# Ref: https://www.drupal.org/project/drupal/issues/2856021#comment-14364115
# @todo: Remove this step once D8 migrates to D9 on test and live.
terminus -n drush "$TERMINUS_SITE.dev" -- cdel language.entity.en

# If there are any exported configuration files, then import them
#if [ -f "config/system.site.yml" ] ; then
  terminus -n drush "$TERMINUS_SITE.dev" -- config-import --yes
#fi

# Delete old multidev environments associated with a PR that has been
# merged or closed.
terminus -n build:env:delete:pr "$TERMINUS_SITE" --yes
